name: flutter_onboarding_app
description: Mock onboading view any with packages
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cache_manager: ^1.0.0+4
  provider: ^6.0.4
  animate_do: ^3.0.2
  sizer: ^2.0.15

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/eatsure_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/images/onboarding_1.png
    - assets/images/onboarding_2.png
    - assets/images/onboarding_3.png

  uses-material-design: true
  fonts:
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Poppins-Bold-Italic
      fonts:
        - asset: assets/fonts/Poppins-BlackItalic.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Poppins-Thin
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf

    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf

    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
